# FlareDrive —— Cloudflare Pages 配置
# 参考：https://developers.cloudflare.com/pages/functions/wrangler-configuration/
name = "flaredrive"
compatibility_date = "2026-08-19"
pages_build_output_dir = "build"
